quarkus.application.name=dnd-companion-server
quarkus.grpc.server.use-separate-server=true
quarkus.grpc.server.port=9000
quarkus.index-dependency.schema.group-id=io.github.arhor.dnd.companion
quarkus.index-dependency.schema.artifact-id=dnd-companion-schema
