package com.github.arhor.spellbindr.ui.feature.characters.sheet.model

import androidx.compose.runtime.Stable
import com.github.arhor.spellbindr.data.model.DamageType

@Stable
data class CharacterSheetCallbacks(
    val onTabSelected: (CharacterSheetTab) -> Unit = {},
    val onEnterEdit: () -> Unit = {},
    val onCancelEdit: () -> Unit = {},
    val onSaveEdits: () -> Unit = {},
    val onAdjustHp: (Int) -> Unit = {},
    val onTempHpChanged: (Int) -> Unit = {},
    val onMaxHpEdited: (String) -> Unit = {},
    val onCurrentHpEdited: (String) -> Unit = {},
    val onTempHpEdited: (String) -> Unit = {},
    val onSpeedEdited: (String) -> Unit = {},
    val onHitDiceEdited: (String) -> Unit = {},
    val onSensesEdited: (String) -> Unit = {},
    val onLanguagesEdited: (String) -> Unit = {},
    val onProficienciesEdited: (String) -> Unit = {},
    val onEquipmentEdited: (String) -> Unit = {},
    val onDeathSaveSuccessesChanged: (Int) -> Unit = {},
    val onDeathSaveFailuresChanged: (Int) -> Unit = {},
    val onSpellSlotToggle: (Int, Int) -> Unit = { _, _ -> },
    val onSpellSlotTotalChanged: (Int, Int) -> Unit = { _, _ -> },
    val onSpellRemoved: (String, String) -> Unit = { _, _ -> },
    val onSpellSelected: (String) -> Unit = {},
    val onAddSpellsClicked: () -> Unit = {},
    val onAddWeaponClicked: () -> Unit = {},
    val onWeaponSelected: (String) -> Unit = {},
    val onWeaponDeleted: (String) -> Unit = {},
    val onWeaponEditorDismissed: () -> Unit = {},
    val onWeaponNameChanged: (String) -> Unit = {},
    val onWeaponAbilityChanged: (String) -> Unit = {},
    val onWeaponUseAbilityForDamageChanged: (Boolean) -> Unit = {},
    val onWeaponProficiencyChanged: (Boolean) -> Unit = {},
    val onWeaponDiceCountChanged: (String) -> Unit = {},
    val onWeaponDieSizeChanged: (String) -> Unit = {},
    val onWeaponDamageTypeChanged: (DamageType) -> Unit = {},
    val onWeaponSaved: () -> Unit = {},
    val onWeaponCatalogOpened: () -> Unit = {},
    val onWeaponCatalogClosed: () -> Unit = {},
    val onWeaponCatalogItemSelected: (String) -> Unit = {},
    val onOpenFullEditor: () -> Unit = {},
    val onDeleteCharacter: () -> Unit = {},
)
