syntax = "proto3";

package dnd.companion.api.v1;

import "catalog.proto";
import "choice.proto";
import "effect.proto";
import "prerequisite.proto";

option java_multiple_files = true;
option java_package = "io.github.arhor.dnd.companion.api.v1";

message Feat {
  string id = 1;
  string name = 2;
  repeated string descriptions = 3 [json_name = "desc"];
  repeated Prerequisite prerequisites = 4;
  repeated Effect effects = 5;
  optional Choice ability_bonus_choice = 6;
  optional Choice language_choice = 7;
  optional Choice proficiency_choice = 8;
  optional Choice damage_type_choice = 9;
  optional Choice maneuver_choice = 10;
  bool correlates_ability_and_saving_throw = 11;
  bool repeatable = 12;
  ResourceMetadata metadata = 13;
}
