syntax = "proto3";

package dnd.companion.api.v1;

import "ability.proto";
import "alignment.proto";
import "background.proto";
import "catalog.proto";
import "character_class.proto";
import "condition.proto";
import "described_data.proto";
import "equipment.proto";
import "feat.proto";
import "feature.proto";
import "language.proto";
import "magic_item.proto";
import "monster.proto";
import "proficiency.proto";
import "public_resources.proto";
import "race.proto";
import "spell.proto";
import "srd_rule.proto";
import "trait.proto";

option java_multiple_files = true;
option java_package = "io.github.arhor.dnd.companion.api.v1";

message ReferenceData {
  repeated Ability abilities = 1;
  repeated Alignment alignments = 2;
  repeated Background backgrounds = 3;
  repeated CharacterClass classes = 4;
  repeated Condition conditions = 5;
  repeated Equipment equipment = 6;
  repeated Feat feats = 7;
  repeated Feature features = 8;
  repeated Language languages = 9;
  repeated MagicItem magic_items = 10;
  repeated MagicSchool magic_schools = 11;
  repeated Proficiency proficiencies = 12;
  repeated Race races = 13;
  repeated RuleSection rule_sections = 14;
  repeated Spell spells = 15;
  repeated Trait traits = 16;
  repeated WeaponProperty weapon_properties = 17;
  repeated SrdRule srd_rules = 18;
  repeated Monster monsters = 19;
}

message CatalogSnapshot {
  CatalogManifest manifest = 1;
  repeated Ruleset rulesets = 2;
  repeated ContentSource sources = 3;
  ReferenceData data = 4;
}
