syntax = "proto3";

package dnd.companion.api.v1;

option java_multiple_files = true;
option java_package = "io.github.arhor.dnd.companion.api.v1";

import "Choice.proto";
import "Catalog.proto";
import "Effect.proto";

message Trait {
  string id = 1;
  string name = 2;
  repeated string desc = 3;
  repeated Effect effects = 4;
  optional Choice spell_choice = 5;
  optional Choice language_choice = 6;
  optional Choice proficiency_choice = 7;
  optional Choice ability_bonus_choice = 8;
  optional Choice draconic_ancestry_choice = 9;
  ResourceMetadata metadata = 10;
}
