[versions]
kotlin = "2.4.0"
quarkus = "3.38.3"

[libraries]
protobuf-kotlin = { module = "com.google.protobuf:protobuf-kotlin" }
quarkus-bom = { module = "io.quarkus.platform:quarkus-bom", version.ref = "quarkus" }
quarkus-grpc = { module = "io.quarkus:quarkus-grpc" }
quarkus-kotlin = { module = "io.quarkus:quarkus-kotlin" }
quarkus-junit = { module = "io.quarkus:quarkus-junit" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
quarkus = { id = "io.quarkus", version.ref = "quarkus" }
