name: Build

on:
  pull_request:
    branches:
      - master
      - stable
    paths:
      - '.github/workflows/android-ci.yml'
      - '.github/workflows/build-and-test-android-client.yml'
      - '.github/actions/**'
      - 'build.gradle.kts'
      - 'settings.gradle.kts'
      - 'gradle.properties'
      - 'gradlew'
      - 'gradlew.bat'
      - 'gradle/**'
      - 'dnd-companion-client-android/**'
    types:
      - opened
      - reopened
      - synchronize
  push:
    branches:
      - master
      - stable
    paths:
      - '.github/workflows/android-ci.yml'
      - '.github/workflows/build-and-test-android-client.yml'
      - '.github/actions/**'
      - 'build.gradle.kts'
      - 'settings.gradle.kts'
      - 'gradle.properties'
      - 'gradlew'
      - 'gradlew.bat'
      - 'gradle/**'
      - 'dnd-companion-client-android/**'
  workflow_dispatch:

permissions:
  contents: read
  issues: write
  pull-requests: write

concurrency:
  group: android-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    name: Build and Test
    uses: ./.github/workflows/build-and-test-android-client.yml
    with:
      application-name: dnd-companion-client-android
    secrets:
      GRADLE_ENCRYPTION_KEY: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
